version: 2

jobs:
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - add_ssh_keys
      - run: ssh -o StrictHostKeyChecking=no -p 10022 ${USER_NAME}@${HOST_NAME} 'cd /home/b-partners01/ano-pla.com/uratabi && git pull && composer require spatie/laravel-permission && php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"'
      - run: php artisan migrate:fresh --seed

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
